### PR TITLE
[Rahul] | BAH-3066 | Add. Filter For Preferred Locale

### PR DESCRIPTION
**Pull request by rahu1ramesh**
Jira Card: [BAH-3066](https://bahmni.atlassian.net/browse/BAH-3066)

This PR addresses the issue related to the report of "type": "formBuilder" in Bahmni. Currently, the report displays concepts in all languages instead of the preferred Locale, and the Fully Specified Name (FSN) is returned instead, even when the Short Name Preferred format is specified.

To resolve these issues, the following changes have been made:
- **Introduction of a new key "preferredLocale"**
This key allows specifying a preferred Locale for the report. When set, the report will display the results in the given Locale, resolving the problem of concepts being displayed in multiple languages.

- **Update of the constructConceptNameSelectSql Method**
The query responsible for displaying concepts in the report has been updated to consider the "conceptNameDisplayFormat" key. This ensures that the report adheres to the specified format, allowing for better customization and consistency.

The `"preferredLocale"` is to be added in the [report.json](https://github.com/Bahmni/default-config/blob/master/openmrs/apps/reports/reports.json) for any form of `"type": "formBuilder"`. If the preferredLocale is not set, the report would display the concepts in all the languages for which translations are available.
Eg : `"preferredLocale": "en" || "preferredLocale": "fr" || "preferredLocale": "es" `

I have attached screenshots of the report with the following configuration:

1. Default (No constraints)
Screenshot 2023-06-26 at 4 10 03 PM

2. "conceptNameDisplayFormat": "shortNamePreferred"
Screenshot 2023-06-26 at 4 09 04 PM

3. "conceptNameDisplayFormat": "shortNamePreferred", "preferredLocale": "en"
Screenshot 2023-06-26 at 4 07 47 PM

4. preferredLocale: "en"
Screenshot 2023-06-26 at 4 06 37 PM

### CODE REVIEW

**Comment by gsluthra** [comment]
So, we were not able to use the user login locale to make this decision in bahmni-reports? That isn't available to us?

**Comment by gsluthra** [comment]
Codewise this is good to merge from my side.

**Comment by gsluthra** [comment]
Will require WIKI documentation on reports.json about this new configuration. https://bahmni.atlassian.net/wiki/spaces/BAH/pages/82837529/Configure+Reports+App

**Comment by rahu1ramesh** [comment]
> So, we were not able to use the user login locale to make this decision in bahmni-reports? That isn't available to us?

In reports, we are not able to access it, the code is relying mostly on querying the global_properties during sql execution.

**Comment by rahu1ramesh** [comment]
> Will require WIKI documentation on reports.json about this new configuration. https://bahmni.atlassian.net/wiki/spaces/BAH/pages/82837529/Configure+Reports+App

Will update the documentation.

**Comment by gsluthra** [comment]
> In reports, we are not able to access it, the code is relying mostly on querying the global_properties during sql execution.

Ok. I guess we should put a card in the backlog to investigate how to get login locale (via some cookie) to bahmni-reports app. Should not be too difficult. Both apps are running in same sub-domain.

**Review by gsluthra — APPROVED** [review]

**Pull request merged**
